# Generated by Django 5.2.5 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("medicines", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="inventorybatch",
            name="opened_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorybatch",
            name="opened_shelf_life_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="inventorybatch",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("opened_at__isnull", True), ("opened_shelf_life_days__isnull", True))
                    | models.Q(("opened_at__isnull", False), ("opened_shelf_life_days__gt", 0))
                ),
                name="inventory_batch_opened_lifetime_consistent",
            ),
        ),
    ]
