# Generated by Django 5.2.5 on 2026-08-08 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_inventorybatch_opened_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryAlertState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threshold_days', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('covered', 'Covered'), ('resolved', 'Resolved'), ('superseded', 'Superseded')], default='pending', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('covered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='medicines.inventorybatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'threshold_days', 'deadline'), name='expiry_alert_state_batch_threshold_deadline_unique')],
            },
        ),
    ]
