# Generated by Django 5.2.5 on 2026-08-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_expirybatchaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirybatchaction',
            name='change_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='expirybatchaction',
            name='action',
            field=models.CharField(choices=[('handled', 'Handled'), ('used_up', 'Used up'), ('corrected', 'Corrected')], max_length=16),
        ),
    ]
