# Generated by Django 5.2.5 on 2026-08-13 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('medicines', '0006_medicineitem_manufacturer_and_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicineitem',
            name='unique_owner_medicine_specification',
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='families.family'),
        ),
        migrations.AlterField(
            model_name='medicineitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='medicineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name', 'specification'), name='unique_owner_medicine_specification'),
        ),
        migrations.AddConstraint(
            model_name='medicineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('family__isnull', False)), fields=('family', 'name', 'specification'), name='unique_family_medicine_specification'),
        ),
        migrations.AddConstraint(
            model_name='medicineitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('owner__isnull', False)), models.Q(('family__isnull', False), ('owner__isnull', True)), _connector='OR'), name='medicine_exactly_one_owner'),
        ),
    ]
