# Generated by Django 5.2.5 on 2026-08-14 08:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_remove_medicineitem_unique_owner_medicine_specification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='loose_units',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='package_unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='unit_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='units_per_package',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loose_units', 0), ('package_unit', ''), ('unit_name', ''), ('units_per_package__isnull', True)), models.Q(models.Q(('package_unit', ''), _negated=True), ('units_per_package__gt', 0), models.Q(('unit_name', ''), _negated=True), ('loose_units__gte', 0)), _connector='OR'), name='inventory_batch_precision_fields_consistent'),
        ),
    ]
