# Generated by Django 5.2.5 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustgrant",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
