# Generated by Django 5.2.5 on 2026-08-08 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_trustgrant_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('attempt', models.PositiveIntegerField()),
                ('result_json', models.JSONField(default=dict)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflows.workflowrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workflow_run', 'node_id', 'attempt'), name='workflow_node_run_attempt_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'claimed', 'sent', 'failed'])), name='workflow_node_run_status_valid'), models.CheckConstraint(condition=models.Q(('attempt__gte', 1)), name='workflow_node_run_attempt_positive')],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_outbox_entries', to='workflows.workflowrun')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'claimed', 'sent', 'failed'])), name='workflow_notification_outbox_status_valid'), models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='workflow_notification_outbox_idempotency_key_nonempty'), models.CheckConstraint(condition=models.Q(models.Q(('claim_token__isnull', False), ('claimed_at__isnull', False), ('lease_expires_at__isnull', False), ('status', 'claimed')), models.Q(models.Q(('status', 'claimed'), _negated=True), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('lease_expires_at__isnull', True)), _connector='OR'), name='workflow_notification_outbox_lease_consistent'), models.CheckConstraint(condition=~models.Q(('status', 'claimed')) | models.Q(('lease_expires_at__gt', models.F('claimed_at'))), name='workflow_notification_outbox_lease_expires_after_claim'), models.CheckConstraint(condition=models.Q(('published_at__isnull', False), ('status', 'sent')) | models.Q(models.Q(('status', 'sent'), _negated=True), ('published_at__isnull', True)), name='workflow_notification_outbox_sent_published')],
            },
        ),
    ]
