# Generated by Django 5.2.5 on 2026-08-08

from django.db import migrations, models


def reject_empty_workflow_run_idempotency_keys(apps, schema_editor):
    WorkflowRun = apps.get_model("workflows", "WorkflowRun")
    if WorkflowRun.objects.using(schema_editor.connection.alias).filter(
        idempotency_key=""
    ).exists():
        raise RuntimeError(
            "Cannot apply workflows 0004: empty idempotency_key values exist; "
            "repair audit data manually before retrying."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_noderun_notificationoutbox"),
    ]

    operations = [
        migrations.RunPython(
            reject_empty_workflow_run_idempotency_keys,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="workflowrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                name="workflow_run_idempotency_key_nonempty",
            ),
        ),
    ]
