# Generated by Django 5.2.5 on 2026-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowrun_idempotency_key_nonempty'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdraft',
            name='clarification_rounds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowdraft',
            name='source_text',
            field=models.TextField(default=''),
        ),
    ]
