# Generated by Django 5.2.5 on 2026-08-03 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=64)),
                ('schedule_json', models.JSONField()),
                ('conditions_json', models.JSONField(default=dict)),
                ('severity', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_rule', to='reminders.reminderdraft')),
            ],
        ),
    ]
