# Generated by Django 5.2.5 on 2026-08-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminderrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceparsesession',
            name='parser_source',
            field=models.CharField(default='local', max_length=32),
        ),
    ]
