# Generated by Django 5.2.5 on 2026-08-08 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage_text', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=64)),
                ('schedule_json', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_plans', to='medicines.medicineitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='pending', max_length=16)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='medication.medicationplan')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('taken', 'Taken'), ('skipped', 'Skipped')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_event', to='medication.medicationoccurrence')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['taken', 'skipped'])), name='medication_intake_event_action_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='medicationplan',
            constraint=models.CheckConstraint(condition=models.Q(('dosage_text', ''), _negated=True), name='medication_plan_dosage_text_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='medicationoccurrence',
            constraint=models.UniqueConstraint(fields=('plan', 'index'), name='medication_occurrence_plan_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='medicationoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'taken', 'skipped', 'missed'])), name='medication_occurrence_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='medicationoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acted_at__isnull', True), ('status', 'pending')), models.Q(('acted_at__isnull', False), ('status__in', ['taken', 'skipped', 'missed'])), _connector='OR'), name='medication_occurrence_action_consistent'),
        ),
        migrations.AddConstraint(
            model_name='medicationoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='medication_occurrence_idempotency_key_nonempty'),
        ),
    ]
