# Generated by Django 5.2.5 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0001_initial"),
        ("workflows", "0004_workflowrun_idempotency_key_nonempty"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationplan",
            name="source_workflow_draft",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medication_plan",
                to="workflows.workflowdraft",
            ),
        ),
    ]
