# Generated by Django 5.2.5 on 2026-08-13 06:31

import django.db.models.deletion
from django.db import migrations, models


def copy_medicine_names(apps, schema_editor):
    MedicationPlan = apps.get_model("medication", "MedicationPlan")
    for plan in MedicationPlan.objects.select_related("medicine").iterator():
        plan.medicine_name = plan.medicine.name
        plan.save(update_fields=["medicine_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_medicationplan_source_workflow_draft'),
        ('medicines', '0007_remove_medicineitem_unique_owner_medicine_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationplan',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(copy_medicine_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='medicationplan',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_plans', to='medicines.medicineitem'),
        ),
    ]
