# Generated by Django 5.2.5 on 2026-08-14 08:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_medicationplan_medicine_name_and_more'),
        ('medicines', '0008_inventorybatch_loose_units_and_more'),
        ('workflows', '0005_workflowdraft_clarification_rounds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDeductionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('deducted', 'Deducted'), ('disabled', 'Disabled'), ('medicine_unlinked', 'Medicine unlinked'), ('not_configured', 'Inventory not configured'), ('unit_mismatch', 'Unit mismatch'), ('insufficient', 'Insufficient inventory'), ('access_denied', 'Access denied')], max_length=32)),
                ('requested_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('deducted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('unit_name', models.CharField(blank=True, max_length=16)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDeductionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('before_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('after_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='auto_deduct_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='dose_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicationplan',
            name='dose_unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='medicationplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dose_quantity__isnull', True), ('dose_unit', '')), models.Q(('dose_quantity__gt', 0), models.Q(('dose_unit', ''), _negated=True)), _connector='OR'), name='medication_plan_structured_dose_consistent'),
        ),
        migrations.AddField(
            model_name='inventorydeductionattempt',
            name='intake_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_deduction_attempt', to='medication.intakeevent'),
        ),
        migrations.AddField(
            model_name='inventorydeductionentry',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='medication.inventorydeductionattempt'),
        ),
        migrations.AddField(
            model_name='inventorydeductionentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_deductions', to='medicines.inventorybatch'),
        ),
        migrations.AddConstraint(
            model_name='inventorydeductionentry',
            constraint=models.UniqueConstraint(fields=('attempt', 'batch'), name='inventory_deduction_attempt_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorydeductionentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_deduction_entry_quantity_positive'),
        ),
    ]
