# Generated by Django 5.2.5 on 2026-08-04 06:17

import apps.ocr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], default='queued', max_length=16)),
                ('image_keys', models.JSONField()),
                ('provider', models.CharField(default='rapidocr', max_length=32)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(default=apps.ocr.models.default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.inventorybatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCRCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=200)),
                ('specification', models.CharField(blank=True, max_length=120)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('confidence_json', models.JSONField(default=dict)),
                ('raw_line_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='ocr.ocrjob')),
            ],
        ),
    ]
